[variables]
# Playwright ကို /root/.cache ထဲမှာ မသွင်းဘဲ Project (.venv) ထဲမှာပဲ သွင်းရန်
PLAYWRIGHT_BROWSERS_PATH = "0"

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install chromium",
  "python -m playwright install-deps chromium"
]

[start]
cmd = "python web_downloader_bot_v17_fixed.py"
